### ISSUE TITLE
get_series() missing

### ISSUE THREAD

**Issue by theotocopulitos** [gpennington/PyMarvel#1]
I am sure you know the .series file is missing ;P

I was wondering if you are still working on this and planning on adding the get_series() method. I am trying to build a comicvine<->marvel equivalence for series...

thanks

**Comment by gpennington** [comment]
Yes. The plan is to fully implement the whole API.  Just kind of taking a while.  Also, I've been refactoring the way resources "talk" to each other, so I wanted to finalize that some before I have to refactor every resource.

Once I cover the basic retrieval of resources, I'll make a release and list it on pypi.  But I'm also trying to stay ahead of test coverage and documentation, so development isn't super fast.  I should have some implementation of series done in a few days, though.  Thanks for posting the question.  Post any other feature requests you might have.

**Comment by theotocopulitos** [comment]
Many thanks, for the work and for the work in this!

**Comment by gpennington** [comment]
The Series (and Story) classes and methods are in master now.  Give it a shot.  Please let me know if you find any issues.

All endpoints listed here are now represented in PyMarvel.  Now I can start adding fun stuff.
http://developer.marvel.com/docs

**Comment by theotocopulitos** [comment]
Thanks Garret, I will have a look at it in the next few days, and let you
know!

Many thanks!
