### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by theotocopulitos** [gpennington/PyMarvel#2]
Hi, I guess line 219 at .core should read

```
    return int(self.dict['returned'])
```

instead of:

```
    return int(elf.dict['returned'])
```

;)

**Comment by gpennington** [comment]
I went ahead and fixed that pushed it up to Master.  I'll probably add a few more features and docs before the next pypi release though.  Thanks for spotting that bug.

If you spot some more bugs or want to add some features, you can fork it and submit a pull request.  That's probably the fastest way to get the things you want into PyMarvel.
