### ISSUE TITLE
str_to_datetime for ComicDate

### ISSUE THREAD

**Issue by fitnr** [gpennington/PyMarvel#5]
ComicDate objects don't have a str_to_datetime

example of the error:

``` python
wrapper = m.get_comics()
wrapper.data.results[0].dates[0].date
```

result:

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/marvel/comic.py", line 251, in date
    return self.str_to_datetime(self.dict['date'])
AttributeError: 'ComicDate' object has no attribute 'str_to_datetime'
```

**Comment by rkuykendall** [comment]
@gpennington I'd love to help cleaning this project up a bit. I'd like to write a PR for this bug, but I notice two pull requests still outstanding. Is there anything I can do to move those two PRs into production?

**Comment by fitnr** [comment]
Closing as stale
