### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by NekoTony** [gpennington/PyMarvel#9]
thanks

**Comment by rkuykendall** [comment]
Hey @Nerdietony, unfortunatly @gpennington is no longer active on Github or responding to emails or tweets. I started a small Marvel API library here: https://github.com/rkuykendall/marvelous and would be happy to add any features or documentation you need to accomplish your goals. What did you have in mind?

**Comment by NekoTony** [comment]
Actually, yeah, does it supply comic book characters and comics information.

**Comment by NekoTony** [comment]
Also, doc link.

**Comment by rkuykendall** [comment]
Marvelous library documentation: http://marvelous.readthedocs.io/en/latest/

**Comment by acupoftee** [comment]
@rkuykendall Thank you for sharing your library with us. Could there be an example as to how you can retrieve a list of characters similar to this library? I saw there was a general function that allowed for custom API calls but I had some trouble with that one. Thanks

**Comment by rkuykendall** [comment]
@bethyd Hey! I think I can help with that. I would make sure you can make the call you want using the [interactive documentation](https://developer.marvel.com/docs) and then I can help show you how to do the same thing in the library. For example, this API call from the interactive docs:
```
https://gateway.marvel.com:443/v1/public/characters/1009610/comics?apikey=MY_KEY_REMOVED
```
Looks like this with the library:
```py
>>> from config import *
>>> import marvelous
>>> m = marvelous.api(public_key, private_key)
>>> character_id = 1009610
>>> api_response = m.call( ['characters', character_id, 'comics'], {'limit': 50})
>>> api_response['data']['results'][0]
{'urls': [{'url': 'http://marvel.com/comics/collection/1308/marvel_age_spider-man_vol_2_everyday_hero_digest?utm_campaign=apiRef&utm_source=8ed19b640c38623fec1c9165da505c4e', 'type': 'detail'}], 'issn': '', 'resourceURI': 'http://gateway.marvel.com/v1/public/comics/1308', 'stories': {'items': [{'resourceURI': 'http://gateway.marvel.com/v1/public/stories/2759', 'name': 'Cover #2759', 'type': 'cover'}, {'resourceURI': 'http://gateway.mar...
```

**Comment by acupoftee** [comment]
@rkuykendall Thank you very much!!
